// src/data/ucfBuildings.ts
const ucfBuildings = [
  'Addition Financial Arena',
  'Arboretum',
  'Art Gallery',
  'Barbara Ying Center',
  'Bennett Research II',
  'Biological Sciences',
  'Business Administration',
  'Business Administration II',
  'Chemistry',
  'Classroom Building I',
  'Classroom Building II',
  'Communication and Media Building',
  'Computer Center',
  'CREOL',
  'Education Complex',
  'Engineering I',
  'Engineering II',
  'Engineering III',
  'Fairwinds Alumni Center',
  'Ferrell Commons',
  'Health and Public Affairs I',
  'Health and Public Affairs II',
  'Harris Engineering Center',
  'John C. Hitt Library',
  'Math and Physics',
  'Mathematical Sciences Building',
  'Memory Mall',
  'Millican Hall',
  'Nicholson School of Communication',
  'Physical Sciences Building',
  'Psychology Building',
  'Recreation and Wellness Center',
  'Research Pavilion',
  'Student Union',
  'Tennis Courts',
  'UCF Global',
  'Visual Arts Building'
];

export default ucfBuildings;
